spring.datasource.url=jdbc:postgresql://localhost:5432/vitallab
spring.datasource.username=postgres
spring.datasource.password=5810
spring.datasource.driver-class-name=org.postgresql.Driver

# Create/update tables automatically (use update in dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
